spring:
  application:
    name: ShoppingApp
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    h2:
      console:
        enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    org:
      springframework:
        data:
          jpa: DEBUG
      hibernate:
        SQL: DEBUG
sql.BasicBinder: TRACE